# Generated by Django 2.1.7 on 2019-03-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doc_design',
            field=models.CharField(default=1.0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='doc_email',
            field=models.CharField(default=(1, 0), max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='doc_exp',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='doc_sex',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
