# Generated by Django 2.1.7 on 2019-03-02 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20190302_0906'),
        ('administration', '0002_auto_20190301_1345'),
    ]

    operations = [
    ]
