# Generated by Django 2.1.7 on 2019-03-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_merge_20190302_0937'),
        ('administration', '0002_auto_20190302_0911'),
    ]

    operations = [
    ]
