# Generated by Django 2.1.7 on 2019-03-02 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_merge_20190302_0456'),
        ('administration', '0004_merge_20190302_1123'),
    ]

    operations = [
    ]
