# Generated by Django 2.1.7 on 2019-03-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_merge_20190302_1634'),
        ('administration', '0005_merge_20190302_1318'),
    ]

    operations = [
    ]
