# Generated by Django 2.1.7 on 2019-03-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_merge_20190302_1227'),
        ('administration', '0006_merge_20190302_1804'),
    ]

    operations = [
    ]
