# Generated by Django 2.1.7 on 2019-02-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('ReceptionID', models.CharField(max_length=30)),
                ('HospitalID', models.CharField(max_length=30)),
                ('EmailID', models.CharField(max_length=50)),
                ('MobileNo', models.CharField(max_length=12)),
                ('Address', models.CharField(max_length=1000)),
                ('Age', models.CharField(max_length=4)),
                ('PatientIDcount', models.IntegerField(default=0)),
            ],
        ),
    ]
