# Generated by Django 2.1.7 on 2019-02-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reception',
            old_name='HospitalID',
            new_name='hos_id',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='PatientIDcount',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='Address',
            new_name='rec_address',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='Age',
            new_name='rec_age',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='EmailID',
            new_name='rec_email_id',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='ReceptionID',
            new_name='rec_id',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='MobileNo',
            new_name='rec_mobile_id',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='Name',
            new_name='rec_name',
        ),
    ]
