# Generated by Django 2.1.7 on 2019-02-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_auto_20190226_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reception',
            old_name='rec_address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='rec_age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='rec_email_id',
            new_name='EmailID',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='hos_id',
            new_name='HospitalID',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='rec_mobile_id',
            new_name='MobileNo',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='rec_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='patient_id',
            new_name='PatientIDcount',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='rec_id',
            new_name='ReceptionID',
        ),
    ]
