# Generated by Django 2.1.7 on 2019-03-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_patient_pat_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_name', models.CharField(max_length=100)),
                ('pat_id', models.CharField(max_length=30)),
                ('hos_id', models.CharField(max_length=30)),
                ('pat_email_id', models.CharField(max_length=50)),
                ('pat_mon_no', models.CharField(max_length=12)),
                ('pat_address', models.CharField(max_length=1000)),
                ('pat_age', models.CharField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='patient1',
        ),
    ]
