# Generated by Django 2.1.7 on 2019-03-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0002_auto_20190301_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindetails',
            name='types',
        ),
        migrations.AlterField(
            model_name='logindetails',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
